Кузьмина Мария. Домашнее задание по урокам 6 и 7.
KuzminaMarya/home-work pull request #5
Opened 2021-11-22 10:32 UTC by KuzminaMarya

@Upforup 
@RodinDenis

Евгений, Денис.

Посмотрите, пож, домашнее задание по 6 и 7 урокам

2021-11-23 20:45 UTC, Upforup requested changes
Предлагаю воспользоваться методом сортировки java.util.List#sort.

2021-11-23 20:45 UTC, Upforup commented on src/main/java/com/sbrf/reboot/AccountUtils.java
> +    public static void sortedById(List<Account> accounts) {
Предлагаю воспользоваться методом сортировки из стандартной библиотеки с использованием Comparator.

2021-11-23 20:45 UTC, Upforup commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        List<Account> accounts = new ArrayList<Account>() {{
Не очень хороший способ создания списка. В такой инициализации создается анонимный подкласс ArrayList.

2021-11-23 20:45 UTC, Upforup commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        Assertions.assertEquals(1L, accounts.get(0).getId());
Списки можно сравнивать по equals: Assertions.assertEquals(Arrays.asList(...), accounts)

2021-11-23 20:56 UTC, KuzminaMarya commented
Спасибо. Завтра попробую исправить замечания.)

2021-11-23 21:43 UTC, KuzminaMarya commented on src/main/java/com/sbrf/reboot/AccountUtils.java
> +    public static void sortedById(List<Account> accounts) {
Сделала

2021-11-23 21:45 UTC, KuzminaMarya commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        List<Account> accounts = new ArrayList<Account>() {{
Исправила на  ArrayList<Account> accounts = new ArrayList<Account>()

2021-11-23 21:49 UTC, KuzminaMarya commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        Assertions.assertEquals(1L, accounts.get(0).getId());
Тут не очень поняла, такое сравнение не работает :( Assertions.assertEquals(Arrays.asList(...), accounts). Наверно надо метод Equals в классе Account реализовывать, чтоб заработало??

2021-11-24 08:28 UTC, KuzminaMarya commented on src/main/java/com/sbrf/reboot/AccountUtils.java
> +    public static void sortedById(List<Account> accounts) {
Поправила

2021-11-24 08:28 UTC, KuzminaMarya commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        List<Account> accounts = new ArrayList<Account>() {{
Поправила

2021-11-24 08:30 UTC, KuzminaMarya commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        Assertions.assertEquals(1L, accounts.get(0).getId());
Не удалось поправить. Не работает сравнение по equals. Надо метод equals реализовать в классе Account, чтоб заработало??

2021-11-24 21:16 UTC, Upforup requested changes

2021-11-24 21:16 UTC, Upforup commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        Assertions.assertEquals(1L, accounts.get(0).getId());
Да, верно

2021-11-24 21:16 UTC, Upforup commented on src/main/java/com/sbrf/reboot/AccountUtils.java
> +    public static void sortedById(List<Account> accounts) {
Просьба реализовать остальные методы сортировки таким же образом

2021-11-24 21:16 UTC, Upforup commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        ArrayList<Account> accounts = new ArrayList<Account>() {{
List<Account> accounts = new ArrayList<>();
        Collections.addAll(accounts,
                Account.builder().id(1L).createDate(LocalDate.now().minusDays(4)).balance(BigDecimal.TEN).build(),
                Account.builder().id(3L).createDate(LocalDate.now().minusDays(3)).balance(BigDecimal.TEN).build(),
                Account.builder().id(3L).createDate(LocalDate.now().minusDays(1)).balance(BigDecimal.TEN).build(),
                Account.builder().id(2L).createDate(LocalDate.now()).balance(BigDecimal.TEN).build()
        );

2021-11-25 06:56 UTC, KuzminaMarya commented on src/test/java/com/sbrf/reboot/utils/AccountUtilsTest.java
> +        Assertions.assertEquals(1L, accounts.get(0).getId());
Исправила

2021-11-25 06:57 UTC, KuzminaMarya commented on src/main/java/com/sbrf/reboot/AccountUtils.java
> +    public static void sortedById(List<Account> accounts) {
Реализовала

2021-11-25 07:45 UTC, Upforup approved these changes
Ок, но в следующем дз, нужно следить за корректной инициализацией коллекций.

2021-11-25 07:45 UTC, Upforup commented on src/main/java/com/sbrf/reboot/Account.java
> +        Account account=(Account)obj;
Почему сравнение только по Id?

2021-11-25 08:19 UTC, KuzminaMarya commented on src/main/java/com/sbrf/reboot/Account.java
> +        Account account=(Account)obj;
добавлю сравнение по балансу и дате создания

2021-11-25 08:38 UTC, KuzminaMarya commented on src/main/java/com/sbrf/reboot/Account.java
> +        Account account=(Account)obj;
Добавила

2021-11-25 08:39 UTC, merged